<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>floatsam_controllers</name>
  <version>0.0.0</version>
  <description>FloatSam USV control stack with cascaded PIDs and captain mixer</description>
  <maintainer email="fidf@kth.se">filippo</maintainer>
  <maintainer email="alebas@kth.se">Alessandro</maintainer>
  <maintainer email="lmanno@kth.se">Bogosbinted</maintainer>
  <license>BSD-3-Clause</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>smarc_msgs</depend>
  <depend>smarc_control_msgs</depend>
  <depend>floatsam_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
