/**/evolo_move_path_action_server:
  ros__parameters:
    frame_id: "evolo/odom"
    timeout: 1200.0

    # Speed
    speed_slow: 4.63
    speed_standard: 4.9
    speed_fast: 6.0
    omega_max: 30.0

    # Pure Pursuit
    ld_base: 20.0
    ld_min: 10.0

    # Dubins planner
    min_turning_radius: 20.0
    dubins_step: 0.5
    dubins_mode: "smooth"  # "vwp" or "smooth"

    # Islands
    hard_buffer: 1.0
    soft_buffer: 15.0
