/**/evolo_move_path_action_server:
  ros__parameters:
    frame_id: "evolo/odom"
    timeout: 1200.0  

    # Speed and limits
    v_min: 8.0
    v_max: 14.0
    omega_max: 16.0

    # Pure Pursuit
    ld_base: 5.0               # Change here
    ld_gain: 0.5
    ff_gain: 0.1

    # Dubins
    min_turning_radius: 30.0    # Change here
    dubins_step: 0.5

    # Buffer
    hard_buffer: 20.0           # Change here
    soft_buffer: 30.0           # Change here

    # Speed Map
    speed_map_slow: 8.0
    speed_map_medium: 11.0
    speed_map_high: 14.0


    # Graph
    graph_type: "voronoi" # 'visibility' ou 'voronoi'



    # Lateral_normal 
    kp_lateral: 0.3
    kp_heading: 0.8
