string BATTERY_TOPIC = 'core/battery'
string GPS_TOPIC = 'core/gps'
string HEADING_TOPIC = 'core/heading'
string ABORT_TOPIC = 'core/abort'
string HEARTBEAT_TOPIC = 'core/heartbeat'
string VEHICLE_READY_TOPIC = 'core/vehicle_ready'

#Topics for all vehicles
string SMARC_ABORT_TOPIC = 'abort'
string SMARC_BT_HEARTBEAT_TOPIC = 'heartbeat'
string SMARC_VEHICLE_HEALTH_TOPIC = 'vehicle_health'
string SMARC_ODOM_TOPIC = 'estimate/odom'
string SMARC_DEPTH_TOPIC = 'estimate/depth'
string SMARC_ALTITUDE_TOPIC = 'estimate/altitude'

################
# WARA-PS Topics
################
## Level 1
string WARA_PS_HEARTBEAT_TOPIC = 'waraps/heartbeat'
string WARA_PS_SENSOR_INFO_TOPIC = 'waraps/sensor_info'
string WARA_PS_SENSOR_POSITION_TOPIC = 'waraps/sensor/position'
string WARA_PS_SENSOR_HEADING_TOPIC = 'waraps/sensor/heading'
string WARA_PS_SENSOR_COURSE_TOPIC = 'waraps/sensor/course'
string WARA_PS_SENSOR_SPEED_TOPIC = 'waraps/sensor/speed'
string WARA_PS_SENSOR_DEPTH_TOPIC = 'waraps/sensor/depth'
string WARA_PS_SENSOR_ROLL_TOPIC = 'waraps/sensor/roll'
string WARA_PS_SENSOR_PITCH_TOPIC = 'waraps/sensor/pitch'

## Level 2
string WARA_PS_DIRECT_EXECUTION_INFO_TOPIC = 'waraps/direct_execution_info'
string WARA_PS_EXEC_RESPONSE_TOPIC = 'waraps/exec/response'
string WARA_PS_EXEC_FEEDBACK_TOPIC = 'waraps/exec/feedback'
string WARA_PS_EXEC_COMMAND_TOPIC = 'waraps/exec/command'
string WARA_PS_ACTION_SERVER_HB_TOPIC = 'waraps/action_server_heartbeat'
