string BATTERY_TOPIC = 'core/battery'
string GPS_TOPIC = 'core/gps'
string HEADING_TOPIC = 'core/heading'
string ABORT_TOPIC = 'core/abort'
string HEARTBEAT_TOPIC = 'core/heartbeat'
string VEHICLE_READY_TOPIC = 'core/vehicle_ready'

#Topics for all vehicles
string SMARC_ABORT_TOPIC = 'abort'
string SMARC_BT_HEARTBEAT_TOPIC = 'heartbeat'
string SMARC_VEHICLE_HEALTH_TOPIC = 'vehicle_health'
string SMARC_ODOM_TOPIC = 'estimate/odom'
string SMARC_DEPTH_TOPIC = 'estimate/depth'
string SMARC_ALTITUDE_TOPIC = 'estimate/altitude'

#Wara PS
string WARA_PS_ACTION_SERVER_HB_TOPIC = 'waraps/action_server_heartbeat'
