selected_topics:
  /M350/sensor/props/fl: "std_msgs/msg/Int16"
  /M350/sensor/props/br: "std_msgs/msg/Int16"
  /M350/sensor/props/fr: "std_msgs/msg/Int16"
  /M350/sensor/props/bl: "std_msgs/msg/Int16"
  /M350/sensor/props/flb: "std_msgs/msg/Int16"
  /M350/sensor/props/frb: "std_msgs/msg/Int16"
  /M350/sensor/props/blb: "std_msgs/msg/Int16"
  /M350/sensor/props/brb: "std_msgs/msg/Int16"
  /M350/base_link_in_map: "geometry_msgs/msg/PoseStamped"
  /M350/wrapper/psdk_ros2/attitude: "geometry_msgs/msg/QuaternionStamped"
  /M350/wrapper/psdk_ros2/velocity_ground_fused: "geometry_msgs/msg/Vector3Stamped"
  /M350/wrapper/psdk_ros2/acceleration_body_fused: "geometry_msgs/msg/AccelStamped"
  /tf_static: "tf2_msgs/msg/TFMessage"
  /M350/wrapper/psdk_ros2/flight_control_setpoint_FLUvelocity_yawrate: "sensor_msgs/msg/Joy"
  /M350/move_to_setpoint: "geometry_msgs/msg/PoseStamped"
  /M350/smarc/odom: "nav_msgs/msg/Odometry"
  /M350/move_to_setpoint : "geometry_msgs/msg/PoseStamped"
  /M350/wrapper/psdk_ros2/attitude : "geometry_msgs/msg/QuaternionStamped"
  /M350/wrapper/psdk_ros2/rc: "sensor_msgs/msg/Joy"