/**/auv_yolo_detector:
  ros__parameters:
    namespace: "M350" #overridden by launch
    device: 'cpu' #overridden by launch

    detection:
      blur_variance: 1.5 #0.01 for not asko, 1.5 for asko
      inference_period: 0.1
      confidence_threshold: 0.4

    sam:
      width: 0.2
      length: 1.5

    topics:
      rviz:
        annotated_image: 'rviz/yolo_annotation'
        bw_blurred_sam: 'rviz/blurred_sam'
        edges: 'rviz/sam_edges'


