nodes:
  - name: "geofence_node"
  - name: "log_action_node"
  - name: "wait_action_node"

topics:
  - topic: "smarc_msgs.msg::Topics.WARA_PS_ACTION_SERVER_HB_TOPIC"
    type: "std_msgs/msg/String"
    qos:
      reliability: reliable
      durability: volatile
      depth: 10
    content:
      field: "data"
      values: 
        - "/M350/smarc_start_geofence"
        - "/M350/smarc_stop_geofence"
        - "/M350/smarc_log"
        - "/M350/smarc_wait"




