#
# DJI Drone links and relevant frames
# Most are published by the dji_captain node
#

string UTM = 'utm'
string MAP = 'map'
string ODOM = 'odom'
string HOME_POINT = 'home_point'

string BASE_LINK = 'base_link'
string BASE_FLAT = 'base_flat_link'
string BASE_ENU = 'base_ENU_link'
string GIMBAL_CAMERA_LINK = 'gimbal_camera_link'


# Used by hook_estimator
string WINCH_LINK = 'winch_link'
string HOOK_LINK = 'hook_link'
