# Used by the dji_captain, namespaced as needed.
# Usually under /M350
string MOVE_TO_SETPOINT_TOPIC = 'move_to_setpoint'
string CONTROLLER_INPUT_TOPIC = 'joy'
string CONTROLLER_VIBRATION_TOPIC = 'joy/set_feedback'
string TTS_TOPIC = 'speak'


string CAMERA_TOPIC = 'Quadrotor/gimbal_camera/image_raw'
string BUOY_TOPIC = 'alars_detection/buoy'
string AUV_TOPIC = 'alars_detection/auv'
string MIDDLE_TOPIC = 'alars_detection/middle'