/**:
  ros__parameters:
    topics:
      input_polygon: "estimated_auv_obb"
      input_auv_head: "estimated_auv_head"
      output_topic: "rviz/estimated_pose"
      odom: "smarc/odom"
      ekf_status: "alars_auv_ekf/status"

    frames:
      map: "map"
      output_link: "estimated_auv"
      camera: "z1_optical_frame"

    camera_info: ""

    environment:
      water_surface_height: 0.0 # height of water surface in map frame.
    
    obb:
      length_m: 1.3 # length of the target obb in meters, may need to be adjusted
      width_m: 0.16 # width of the target obb in meters, may need to be adjusted

    alpha_line_pixels: 40 # number of pixels along length of obb to use for alpha (yaw) measurement in initialization.

    motion:
      sigma_a_xy: 0.01 # acc
      sigma_a_z: 1.0 # acc
      sigma_yaw: 3.0 # random walk in yaw
      sigma_a_pitch: 15.0 # acc in pitch (deg/s^2)
      model_type: "double_oscillator" # options: "surface", "depth", "pitch", "oscillator", "double_oscillator"

    # measurement noise parameters, note that u is right in the image (x), v is down in the image (y).
    measurement_noise:
      R_u: 10.0 # measurement noise for target center u image coordinate (pixels)
      R_v: 10.0 # measurement noise for target center v image coordinate (pixels)
      R_alpha_deg: 5.0 # measurement noise for target center alpha (yaw) coordinate (degrees)
      R_len: 100.0 # measurement noise for target center length coordinate (pixels). As pitch is not included in the state model (except for pitchmodel), pitch is modeled as noise on the length observation.
      R_wid: 40.0 # measurement noise for target center width coordinate (pixels)

      center_gain_u: 50.0 # measurement noise gain for distance from center in u direction, for example if the image has high distortion / bad calibration.
      center_gain_v: 50.0 # measurement noise gain for distance from center in v direction.
      center_gain_alpha_deg: 10.0 # measurement noise gain for distance from center in alpha (yaw) direction (degrees).
      center_gain_len: 50.0 # measurement noise gain for distance from center in length direction.
      center_gain_wid: 50.0 # measurement noise gain for distance from center in width direction.

      speed_gain_u: 50.0 # measurement noise gain in target center u coordinate () from uav speed 
      speed_gain_v: 50.0 # measurement noise gain in target center v coordinate () from uav speed
      speed_gain_alpha_deg: 10.0 # measurement noise gain in target center alpha (yaw) coordinate () from uav speed (degrees)
      speed_gain_len: 60.0 # measurement noise gain in target center length coordinate () from uav speed 
      speed_gain_wid: 30.0 # measurement noise gain in target center width coordinate () from uav speed 

      R_dyn_dt: 0.5 # noise in time of measurement, say if there is a delay / incorrect timestamp, while target or camera is moving.

    # noise of camera pose. This is used in the measurement model to account for the fact that the measurement is taken in the camera frame, but the camera pose is not perfectly known, may need adjustment.
    camera_pose_noise:
      R_pose_x: 0.03 # noise in x position of camera/auv pose (meters)
      R_pose_y: 0.03 # noise in y position of camera/auv pose (meters)
      R_pose_z: 0.03 # noise in z position of camera/auv pose (meters)
      R_pose_r: 1.0 # noise in roll angle of camera/auv pose (degrees)
      R_pose_p: 1.0 # noise in pitch angle of camera/auv pose (degrees)
      R_pose_yaw: 3.0 # noise in yaw angle of camera/auv pose (degrees)

    initialization:
      min_valid_meas_needed: 5 # minimum number of consequtive measurements with low enough spreald to initialize the filter.
      max_pos_spread: 2.0 # maximum spread in position measurements for initialization (meters).
      max_yaw_spread: 30.0 # maximum spread in yaw measurements for initialization (degrees).

    gating:
      prob: 0.99 # gating probability for Mahalanobis distance gating, may need to be adjusted based on measurement noise and outliers.

    jacobian:
      eps_state_pos: 0.001
      eps_state_yaw: 0.001
      eps_state_vel: 0.001
      eps_pose_pos: 0.001
      eps_pose_ang: 0.001

    logger_info:
      enable: true

    stale_state_age: 3.0