/**:
  ros__parameters:
    topics:
      input_polygon: "estimated_auv_obb"
      input_auv_head: "estimated_auv_head"
      output_topic: "rviz/estimated_pose"
      odom: "smarc/odom"
      ekf_status: "alars_auv_ekf/status"

    frames:
      map: "map"
      output_link: "estimated_auv"
      camera: "z1_optical_frame"

    camera_info: ""

    z_water: 0.0
    n_air: 1.0
    n_water: 1.0

    obb.length_m: 1.3
    obb.width_m: 0.16

    alpha_line_pixels: 40.0

    sigma_a: 0.01 # acc
    sigma_z_process: 0.2 # acc
    sigma_yaw_process: 3.0
    sigma_pitch_acc_deg: 15.0

    R_u: 10.0
    R_v: 10.0
    R_alpha_deg: 5.0
    R_len: 100.0
    R_wid: 40.0

    R_dyn.center_gain_u: 50.0
    R_dyn.center_gain_v: 50.0
    R_dyn.center_gain_alpha_deg: 10.0
    R_dyn.center_gain_len: 10.0
    R_dyn.center_gain_wid: 10.0

    R_dyn.speed_gain_u: 50.0
    R_dyn.speed_gain_v: 50.0
    R_dyn.speed_gain_alpha_deg: 10.0
    R_dyn.speed_gain_len: 60.0
    R_dyn.speed_gain_wid: 30.0

    R_pose_x: 0.03
    R_pose_y: 0.03
    R_pose_z: 0.03
    R_pose_r: 1.0
    R_pose_p: 1.0
    R_pose_yaw: 3.0

    R_dyn_dt: 0.5

    init_z_needed: 5
    init_pos_max_spread: 2.0
    init_yaw_max_spread: 0.7
    init_z_max_spread: 2.0
    init_min_depth: 0.2
    init_max_depth: 8.0
    init_depth_steps: 40

    gating.prob: 0.99

    logger_info.enable: true

    jacobian.eps_state_pos: 0.001
    jacobian.eps_state_yaw: 0.001
    jacobian.eps_state_vel: 0.001
    jacobian.eps_pose_pos: 0.001
    jacobian.eps_pose_ang: 0.001

    motion_model: "oscillator" # options: "surface", "depth", "pitch", "oscillator"