---
/*/**:
  ros__parameters:
    debug_imshow: 0
    enable_buoy_detector: 1
    enable_auv_detector: 1
    enable_rope_detector: 0
    enable_on_start: 1
    buoy_color_lower_orange: [8, 121, 35]
    buoy_color_upper_orange: [40, 157, 247]
    auv_color_lower_yellow: [25, 0, 169]
    auv_color_upper_yellow: [46, 103, 221]
    calibration_altitude: 8.7
    buoy_area_percent_at_calibration_altitude: 0.007
    auv_area_percent_at_calibration_altitude: 0.149
    sensitivity_area_percent: 0.10
    least_area_pixels: 10