# .github/workflows/build-and-test-humble.yaml

name: Build ROS2 Humble workspace(and run tests)

on:
  push:
    branches: [humble, gh_workflow_testing]
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
    - 'docker/**'
    - 'documentation/**'
    - 'drivers/**'
    - 'simulation/**'
    - 'LICENSE'
    - '.gitignore'
  pull_request:
    branches: [humble, gh_workflow_testing]
    paths-ignore:
    - '**/*.md'
    - 'docs/**'
    - 'docker/**'
    - 'documentation/**'
    - 'drivers/**'
    - 'simulation/**'
    - 'LICENSE'
    - '.gitignore'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v7
        with: 
            path: colcon_ws/src/${{ github.event.repository.name }}

      - name: Install ROS 2 Humble
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common curl
          sudo add-apt-repository universe

          export ROS_APT_SOURCE_VERSION=$(
            curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest \
            | grep -F "tag_name" \
            | awk -F'"' '{print $4}'
          )

          curl -L -o /tmp/ros2-apt-source.deb \
            "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.jammy_all.deb"

          sudo dpkg -i /tmp/ros2-apt-source.deb

          # GitHub ubuntu-22.04 runners may contain LLVM's versioned
          # libunwind development package, which conflicts with Ubuntu's
          # libunwind-dev required by GStreamer.
          sudo apt-get remove -y \
          libunwind-13-dev \
          libunwind-14-dev \
          libunwind-15-dev || true

          sudo apt-get update
          sudo apt-get install -y \
            ros-humble-ros-base \
            ros-dev-tools \
            libunwind-dev

      - name: Check ROS
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          ros2 --help


      - name: Get base submodules
        shell: bash
        working-directory: colcon_ws/src/${{ github.event.repository.name }}
        run: |
            git submodule update --init external_packages/mqtt_bridge/
            git submodule update --init external_packages/ROS-TCP-Endpoint/


      - name: Get ALARS submodules and dependencies
        shell: bash
        working-directory: colcon_ws/src/${{ github.event.repository.name }}
        run: |
            git submodule update --init messages/psdk_interfaces


      - name: Rosdep
        shell: bash
        working-directory: colcon_ws
        run: |
          sudo apt-get install -y python3-rosdep
          sudo rosdep init
          rosdep update
          source /opt/ros/humble/setup.bash
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build workspace
        shell: bash
        working-directory: colcon_ws
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install

      - name: Run dji_bringup.sh
        shell: bash
        working-directory: colcon_ws
        run: |
          source install/setup.bash
          export ROS_DOMAIN_ID=1
          ros2 run smarc_bringups dji_bringup.sh M350 15.0 testing
          echo "Waiting for dji_bringup.sh to start..."
          sleep 10
          echo ">>>> ROS NODES"
          ros2 node list

      - name: Test dji_captain topics
        shell: bash
        working-directory: colcon_ws
        run: |
          source install/setup.bash
          export ROS_DOMAIN_ID=1
          ros2 run expect_topics expect_topics --ros-args -p timeout_sec:=600.0 -p topics_file:=dji_captain.yaml -r __ns:=/M350

      - name: Kill tmux server
        if: always()
        shell: bash
        working-directory: colcon_ws
        run: |
          tmux kill-server

          
